default_config:
  mode: MASKING

tables:
  - table_name_with_schema: "TEST.FILM"
    transformations:
      - columns: [ "RATING" ]
        params:
          type: "categorical_generator"
      - columns: [ "SPECIAL_FEATURES" ]
        params:
          type: "categorical_generator"
          categories:
            value_source: PROVIDED
            values:
              "Trailers": 223
              "Commentaries": 21
              "Deleted Scenes": 195
              "Behind the Scenes": 194

cycle_resolution_strategy: DEFER_FOREIGN_KEY
table_truncation_mode: TRUNCATE
schema_creation_mode: CREATE_IF_NOT_EXISTS
safety_mode: "RELAXED"
