version: '3.5'

services:

  input_db:
    container_name: input_db
    image: ibmcom/db2
    privileged: true
    environment:
      LICENSE: accept
      DB2INST1_PASSWORD: test
      SAMPLEDB: "true"
      DBNAME: testdb
    ports: [ "6000:50000" ]
    healthcheck:
      test: /opt/ibm/db2/V11.5/bin/db2 CONNECT TO $$DBNAME
      interval: 5s
      timeout: 240s
      start_period: 10s


  output_db:
    container_name: output_db
    image: ibmcom/db2
    privileged: true
    environment:
      LICENSE: accept
      DB2INST1_PASSWORD: test
      SAMPLEDB: "false"
      DBNAME: testdb
    ports: [ "6001:50000" ]
    healthcheck:
      test: /opt/ibm/db2/V11.5/bin/db2 CONNECT TO $$DBNAME
      interval: 5s
      timeout: 240s
      start_period: 10s


  tdk:
    extends:
      file: ../parent-compose.yml
      service: tdk
    environment:
      SYNTHESIZED_INPUT_URL: jdbc:db2://input_db:50000/SAMPLE
      SYNTHESIZED_INPUT_USERNAME: DB2INST1
      SYNTHESIZED_INPUT_PASSWORD: test
      SYNTHESIZED_OUTPUT_URL: jdbc:db2://output_db:50000/testdb
      SYNTHESIZED_OUTPUT_USERNAME: DB2INST1
      SYNTHESIZED_OUTPUT_PASSWORD: test
      SYNTHESIZED_USERCONFIG_FILE: /app/config.yaml
      TDK_WORKINGDIRECTORY_PATH: /app/data
      TDK_WORKINGDIRECTORY_ENABLED: "true"
      SYNTHESIZED_KEY: ${SYNTHESIZED_KEY}
      JAVA_TOOL_OPTIONS: >
        -Dlogging.level.io.synthesized.tdk.executor.lite.LiteTransformer=INFO
        -Dlogging.level.io.synthesized.tdk=WARN
        -Dlogging.level.com.zaxxer.hikari=WARN
        -Dlogging.level.org.reflections=WARN
        -Dlogging.level.org.jooq=WARN
        -XX:+UseContainerSupport
        -XX:MaxRAMPercentage=80.0
        -Dspring.main.banner-mode=CONSOLE
        -Dspring.banner.location=file:/app/banner.txt
    volumes:
      - ./${CONFIG_FILE:-config_masking.tdk.yaml}:/app/config.yaml
      - ../banner.txt:/app/banner.txt
      - ../logback-lite-executor.xml:/app/logback-lite-executor.xml
