default_config:
  mode: GENERATION
  target_ratio: 2.0

tables:

  - table_name_with_schema: "sakila.film"
    transformations:
      - columns: ["rating"]
        params:
          type: "categorical_generator"
          categories:
            type: STRING
            value_source: PROVIDED
            values:
              "PG-13": 0.223
              "NC-17": 0.21
              "R": 0.195
              "PG": 0.194
              "G": 0.178

  - table_name_with_schema: "sakila.actor"
    transformations:
      - columns: ["first_name", "last_name"]
        # An example how to preserve the uppercase
        mapping:
          read: "?"
          write: "UPPER(?)"
        params:
          type: person_generator
          column_templates: ["${first_name}", "${last_name}"]

  - table_name_with_schema: "sakila.country"
    transformations:
      - columns: [ "country" ]
        params:
          type: address_generator
          column_templates: [ "${country}" ]

  - table_name_with_schema: "sakila.city"
    transformations:
      - columns: [ "city" ]
        params:
          type: address_generator
          column_templates: [ "${city}" ]

  - table_name_with_schema: "sakila.address"
    transformations:
      - columns: [ "address", "address2" ]
        params:
          type: address_generator
          column_templates:
            - "${street_name}, ${house_number}, ${flat_number}, ${zip_code}"
            - >
              ${country}, ${city}, ${street_name}, ${house_number},
              ${flat_number}, ${zip_code}
          length_exceeded_mode: "TRUNCATE"

  - table_name_with_schema: "sakila.staff"
    transformations:
      - columns: ["first_name", "last_name", "email"]
        params:
          type: person_generator
          column_templates: ["${first_name}", "${last_name}", "${email}"]

  - table_name_with_schema: "sakila.customer"
    transformations:
      - columns: ["first_name", "last_name", "email"]
        params:
          type: person_generator
          column_templates: ["${first_name}", "${last_name}", "${email}"]

  - table_name_with_schema: "sakila.rental"
    transformations:
      - columns: [ "rental_date" ]
        params:
          type: "date_generator"
          mean: 2022-03-01T12:00:00Z
          std: 7776000000
          min: 2022-01-01T12:00:00Z
          max: 2022-07-01T12:00:00Z

table_truncation_mode: "TRUNCATE"
schema_creation_mode: "DROP_AND_CREATE"
cycle_resolution_strategy: "DELETE_NOT_REQUIRED"
safety_mode: "RELAXED"
