default_config:
  mode: GENERATION
  target_ratio: 2.0

table_truncation_mode: "TRUNCATE"
schema_creation_mode: "DROP_AND_CREATE"
cycle_resolution_strategy: "DELETE_NOT_REQUIRED"
safety_mode: "RELAXED"
