default_config:
  mode: GENERATION
  target_row_number: 1000

tables:
  - table_name_with_schema: "public.country"
    target_row_number: 200
    transformations:
      - columns: [ "country" ]
        params:
          type: address_generator
          column_templates: [ "${country}" ]

  - table_name_with_schema: "public.language"
    target_row_number: 100

  - table_name_with_schema: "public.city"
    target_row_number: 500
    transformations:
      - columns: [ "city" ]
        params:
          type: address_generator
          column_templates: [ "${city}" ]

  - table_name_with_schema: "public.address"
    target_row_number: 1_000
    transformations:
      - columns: [ "address", "address2" ]
        params:
          type: address_generator
          column_templates:
            - "${street_name}, ${house_number}, ${flat_number}, ${zip_code}"
            - >
              ${country}, ${city}, ${street_name}, ${house_number},
              ${flat_number}, ${zip_code}

  - table_name_with_schema: "public.store"
    target_row_number: 1_000

  - table_name_with_schema: "public.staff"
    target_row_number: 5_000
    transformations:
      - columns: ["first_name", "last_name", "email"]
        params:
          type: person_generator
          column_templates: ["${first_name}", "${last_name}", "${email}"]

  - table_name_with_schema: "public.customer"
    target_row_number: 10_000
    transformations:
      - columns: ["first_name", "last_name", "email"]
        params:
          type: person_generator
          column_templates: ["${first_name}", "${last_name}", "${email}"]

  - table_name_with_schema: "public.film"
    target_row_number: 3_000
    transformations:
      - columns: ["fulltext"]
        mapping:
          read: "?::text"
          write: "?::tsvector"
        params:
          type: formatted_string_generator
          pattern: "\\+44[0-9]{10}"
      - columns: ["rating"]
        mapping:
          read: "?::text"
          write: "?::mpaa_rating"
        params:
          type: "categorical_generator"
          categories:
            type: STRING
            value_source: PROVIDED
            values:
              "PG-13": 0.223
              "NC-17": 0.21
              "R": 0.195
              "PG": 0.194
              "G": 0.178

  - table_name_with_schema: "public.rental"
    target_row_number: 20_000
    transformations:
      - columns: [ "rental_date" ]
        params:
          type: "date_generator"
          mean: 2022-03-01T12:00:00Z
          std: 2d 4h 45m 12s 434ms

  - table_name_with_schema: "public.payment"
    target_row_number: 20_000
    transformations:
      - columns: [ "payment_date" ]
        params:
          type: "date_generator"
          mean: 2022-03-01T12:00:00Z
          std: 2d 4h 45m 12s 434ms


table_truncation_mode: "TRUNCATE"
schema_creation_mode: "CREATE_IF_NOT_EXISTS"
cycle_resolution_strategy: "DELETE_NOT_REQUIRED"
safety_mode: "RELAXED"
