default_config:
  mode: KEEP
  use_working_directory: true

tables:

  - table_name_with_schema: "public.rental"
    target_ratio: 0.1

  - table_name_with_schema: "public.payment"
    target_ratio: 0.1

schema_creation_mode: "DROP_AND_CREATE"
safety_mode: "RELAXED"
