name: test_mssqlserver

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ '*' ]

defaults:
  run:
    working-directory: ./mssqlserver

jobs:

  masking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build docker compose
        run: |
          docker compose pull
          docker compose build

      - name: Run databases test
        continue-on-error: true
        timeout-minutes: 5
        run: |
          docker compose run databases

      - name: Run databases ls
        continue-on-error: true
        run: |
          docker ps -a

      - name: Run databases logs
        continue-on-error: true
        run: |
          docker compose logs

      - name: Run databases ls 2
        continue-on-error: true
        run: |
          docker inspect input_db

      - name: Run databases ls 3
        continue-on-error: true
        run: |
          docker inspect output_db

      - name: Run databases
        run: |
          docker compose run databases

      - name: Run TDK
        run: |
          export CONFIG_FILE=config_masking.tdk.yaml
          docker compose run tdk
