name: test_sqlite

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

defaults:
  run:
    working-directory: ./sqlite

jobs:

  generation_from_scratch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build docker-compose
        run: |
          docker-compose pull
          docker-compose build

      - name: Run the workflow
        run: |
          export CONFIG_FILE=config_keep.tdk.yaml
          docker-compose run tdk
